# -*- coding: utf-8 -*-
"""gemini_api_with_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AiZsRV1yOWwJ2cruj0IHcu12UK2Y1U_I
"""

!pip install -q -U google-generativeai

!pip install Ipython

import google.generativeai as genai
import pathlib
import textwrap
from IPython.display import display
from IPython.display import Markdown

def to_markdown(text):
  text = text.replace('• ',' *')
  return Markdown(textwrap.indent(text,'> ',predicate = lambda _: True))

input_text = "This is a - sample text with bullet points"
results = to_markdown(input_text)
display(results)

from google.colab import userdata

GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY').strip()

genai.configure(api_key = GOOGLE_API_KEY)

for model in genai.list_models():
  print(model)

for models in genai.list_models():
  if 'generateContent' in models.supported_generation_methods:
    print(models.name)

model = genai.GenerativeModel('gemini-pro')

# Commented out IPython magic to ensure Python compatibility.
# %%time
# response = model.generate_content("What is the meaning of life?")

response.text.split('\n')

